name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: [ ubuntu-24.04-arm ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.4
          govulncheck ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.10.1

  build-and-test:
    strategy:
      fail-fast: false
      matrix: 
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest ]
        include:
          - os: windows-latest
            docker_host: ssh://test@localhost:2222
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install WSL (Windows)
        if: runner.os == 'Windows'
        uses: Vampire/setup-wsl@6a8db447be7ed35f2f499c02c6e60ff77ef11278 # v6
        with:
          distribution: Ubuntu-24.04
          additional-packages: |
            openssh-server
            docker.io
      
      - name: Setup SSH (Windows - WSL)
        if: runner.os == 'Windows'
        shell: wsl-bash {0}
        run: |
          useradd -G kvm,docker -m -s /bin/bash test
          passwd -d test

          cat > /etc/ssh/sshd_config.d/01-passwordless-authentication.conf << 'EOF'
          PasswordAuthentication yes
          PermitEmptyPasswords yes
          UsePAM no
          Port 2222
          EOF
          
          systemctl daemon-reload
          systemctl restart ssh

      - name: Add WSL host key (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Keep WSL running
          wsl --exec dbus-launch true
          #  Windows ssh-keyscan has KexAlgorithm limitations so use ssh to add host key - https://github.com/PowerShell/Win32-OpenSSH/issues/2140
          ssh -p 2222 -o StrictHostKeyChecking=accept-new test@localhost "exit"

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Build
        run: |
          go build -v ./cmd/topo

      - name: Run tests with coverage
        env: 
          DOCKER_HOST: ${{ matrix.docker_host }}
        run: |
          go test ./... -p 1 -v -covermode=atomic -coverprofile=coverage.out
