name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: v2.7.2

  build-and-test:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: true
          cache-dependency-path: |
            **/go.sum

      - name: Build
        run: |
          go build -v ./cmd/topo

      - name: Set up Lima
        uses: lima-vm/lima-actions/setup@55627e31b78637bf254a8b2a14da8ea7d12564e5 # v1.1.0
        id: lima-actions-setup

      - name: Cache ~/.cache/lima
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/lima
          key: lima-${{ steps.lima-actions-setup.outputs.version }}

      - name: Run tests with coverage
        run: |
          go test ./... -v -covermode=atomic -coverprofile=coverage.out

      - name: Install Qlty Cloud
        uses: qltysh/qlty-action/install@v2.2.0

      - name: Upload coverage to Qlty Cloud
        uses: qltysh/qlty-action/coverage@v2.2.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage.out
          strip-prefix: github.com/arm-debug/topo-cli/
